### ISSUE TITLE
Can't add Travis CI

### ISSUE THREAD

**Issue by whithajess** [steakunderscore/cake-day-register#4]
Not in my Repos/Organistations @steakunderscore can you start one? Ill add the config

**Comment by whithajess** [comment]
Or just let me have access to do it @Pamplemousse says you can add the settings for webhooks etc. Cheers

**Comment by steakunderscore** [comment]
Hey guys! I have switched on travis CI for this repo. I'll also switch on Hound too if you like?

I don't think that I can give access the settings of a personal repo. I think Github tries to for the use of groups.

**Comment by whithajess** [comment]
Hey man cheers what is Hound?

**Comment by steakunderscore** [comment]
https://robots.thoughtbot.com/introducing-hound
